<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderItemsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('order_items')->insert([
            ['id' => 7, 'order_id' => 5, 'purchasable_id' => 5, 'cart_item_id' => 16, 'title' => 'Pijama Confort Nube Nueve', 'slug' => 'pijama-confort-nube-nueve', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3200, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3200, 'total_with_taxes' => 3680, 'computed_taxes' => 480, 'created_at' => '2026-04-06 20:04:08', 'updated_at' => '2026-04-06 20:04:08', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 8, 'order_id' => 5, 'purchasable_id' => 1, 'cart_item_id' => 15, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 9600, 'total_with_taxes' => 11040, 'computed_taxes' => 1440, 'created_at' => '2026-04-06 20:04:08', 'updated_at' => '2026-04-06 20:04:08', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 9, 'order_id' => 6, 'purchasable_id' => 1, 'cart_item_id' => 17, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-07 00:47:11', 'updated_at' => '2026-04-07 00:47:11', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 10, 'order_id' => 6, 'purchasable_id' => 5, 'cart_item_id' => 18, 'title' => 'Pijama Confort Nube Nueve', 'slug' => 'pijama-confort-nube-nueve', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3200, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 6400, 'total_with_taxes' => 7360, 'computed_taxes' => 960, 'created_at' => '2026-04-07 00:47:11', 'updated_at' => '2026-04-07 00:47:11', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 11, 'order_id' => 7, 'purchasable_id' => 1, 'cart_item_id' => 19, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-07 01:07:57', 'updated_at' => '2026-04-07 01:07:57', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 12, 'order_id' => 7, 'purchasable_id' => 4, 'cart_item_id' => 20, 'title' => 'Chaleco Aislado Antártico', 'slug' => 'chaleco-aislado-antartico', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3500, 'total_with_taxes' => 4025, 'computed_taxes' => 525, 'created_at' => '2026-04-07 01:07:57', 'updated_at' => '2026-04-07 01:07:57', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 13, 'order_id' => 8, 'purchasable_id' => 3, 'cart_item_id' => 22, 'title' => 'Cortavientos Transpirable Pionero', 'slug' => 'cortavientos-transpirable-pionero', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3900, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3900, 'total_with_taxes' => 4485, 'computed_taxes' => 585, 'created_at' => '2026-04-07 01:09:22', 'updated_at' => '2026-04-07 01:09:22', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 14, 'order_id' => 8, 'purchasable_id' => 2, 'cart_item_id' => 21, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 5000, 'total_with_taxes' => 5750, 'computed_taxes' => 750, 'created_at' => '2026-04-07 01:09:22', 'updated_at' => '2026-04-07 01:09:22', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 15, 'order_id' => 9, 'purchasable_id' => 2, 'cart_item_id' => 23, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 01:12:08', 'updated_at' => '2026-04-07 01:12:08', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 16, 'order_id' => 9, 'purchasable_id' => 5, 'cart_item_id' => 24, 'title' => 'Pijama Confort Nube Nueve', 'slug' => 'pijama-confort-nube-nueve', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3200, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3200, 'total_with_taxes' => 3680, 'computed_taxes' => 480, 'created_at' => '2026-04-07 01:12:08', 'updated_at' => '2026-04-07 01:12:08', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 17, 'order_id' => 10, 'purchasable_id' => 2, 'cart_item_id' => 25, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 01:19:42', 'updated_at' => '2026-04-07 01:19:42', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 18, 'order_id' => 10, 'purchasable_id' => 3, 'cart_item_id' => 26, 'title' => 'Cortavientos Transpirable Pionero', 'slug' => 'cortavientos-transpirable-pionero', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3900, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3900, 'total_with_taxes' => 4485, 'computed_taxes' => 585, 'created_at' => '2026-04-07 01:19:42', 'updated_at' => '2026-04-07 01:19:42', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 19, 'order_id' => 11, 'purchasable_id' => 1, 'cart_item_id' => 27, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-07 01:27:32', 'updated_at' => '2026-04-07 01:27:32', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 20, 'order_id' => 11, 'purchasable_id' => 2, 'cart_item_id' => 28, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 01:27:32', 'updated_at' => '2026-04-07 01:27:32', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 21, 'order_id' => 12, 'purchasable_id' => 1, 'cart_item_id' => 29, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-07 01:35:11', 'updated_at' => '2026-04-07 01:35:11', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 22, 'order_id' => 12, 'purchasable_id' => 2, 'cart_item_id' => 30, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 01:35:11', 'updated_at' => '2026-04-07 01:35:11', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 23, 'order_id' => 13, 'purchasable_id' => 4, 'cart_item_id' => 32, 'title' => 'Chaleco Aislado Antártico', 'slug' => 'chaleco-aislado-antartico', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3500, 'total_with_taxes' => 4025, 'computed_taxes' => 525, 'created_at' => '2026-04-07 16:14:56', 'updated_at' => '2026-04-07 16:14:56', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 24, 'order_id' => 13, 'purchasable_id' => 2, 'cart_item_id' => 31, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 5000, 'total_with_taxes' => 5750, 'computed_taxes' => 750, 'created_at' => '2026-04-07 16:14:56', 'updated_at' => '2026-04-07 16:14:56', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 25, 'order_id' => 14, 'purchasable_id' => 2, 'cart_item_id' => 33, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 17:24:49', 'updated_at' => '2026-04-07 17:24:49', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 26, 'order_id' => 14, 'purchasable_id' => 4, 'cart_item_id' => 34, 'title' => 'Chaleco Aislado Antártico', 'slug' => 'chaleco-aislado-antartico', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3500, 'total_with_taxes' => 4025, 'computed_taxes' => 525, 'created_at' => '2026-04-07 17:24:49', 'updated_at' => '2026-04-07 17:24:49', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 27, 'order_id' => 15, 'purchasable_id' => 2, 'cart_item_id' => 35, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 5000, 'total_with_taxes' => 5750, 'computed_taxes' => 750, 'created_at' => '2026-04-07 17:52:45', 'updated_at' => '2026-04-07 17:52:45', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 28, 'order_id' => 15, 'purchasable_id' => 16, 'cart_item_id' => 36, 'title' => 'Lounge Time', 'slug' => 'lounge-time', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2300, 'quantity' => 3, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 6900, 'total_with_taxes' => 7935, 'computed_taxes' => 1035, 'created_at' => '2026-04-07 17:52:45', 'updated_at' => '2026-04-07 17:52:45', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 29, 'order_id' => 16, 'purchasable_id' => 4, 'cart_item_id' => 37, 'title' => 'Chaleco Aislado Antártico', 'slug' => 'chaleco-aislado-antartico', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3500, 'total_with_taxes' => 4025, 'computed_taxes' => 525, 'created_at' => '2026-04-07 17:56:00', 'updated_at' => '2026-04-07 17:56:00', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 30, 'order_id' => 16, 'purchasable_id' => 5, 'cart_item_id' => 38, 'title' => 'Pijama Confort Nube Nueve', 'slug' => 'pijama-confort-nube-nueve', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3200, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 6400, 'total_with_taxes' => 7360, 'computed_taxes' => 960, 'created_at' => '2026-04-07 17:56:00', 'updated_at' => '2026-04-07 17:56:00', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 31, 'order_id' => 17, 'purchasable_id' => 1, 'cart_item_id' => 39, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-07 18:01:16', 'updated_at' => '2026-04-07 18:01:16', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 32, 'order_id' => 17, 'purchasable_id' => 2, 'cart_item_id' => 40, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 18:01:16', 'updated_at' => '2026-04-07 18:01:16', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 33, 'order_id' => 18, 'purchasable_id' => 16, 'cart_item_id' => 42, 'title' => 'Lounge Time', 'slug' => 'lounge-time', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2300, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2300, 'total_with_taxes' => 2645, 'computed_taxes' => 345, 'created_at' => '2026-04-07 19:44:59', 'updated_at' => '2026-04-07 19:44:59', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 34, 'order_id' => 18, 'purchasable_id' => 2, 'cart_item_id' => 41, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 3, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 7500, 'total_with_taxes' => 8625, 'computed_taxes' => 1125, 'created_at' => '2026-04-07 19:44:59', 'updated_at' => '2026-04-07 19:47:27', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 35, 'order_id' => 19, 'purchasable_id' => 3, 'cart_item_id' => 44, 'title' => 'Cortavientos Transpirable Pionero', 'slug' => 'cortavientos-transpirable-pionero', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3900, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3900, 'total_with_taxes' => 4485, 'computed_taxes' => 585, 'created_at' => '2026-04-07 14:54:57', 'updated_at' => '2026-04-07 14:54:57', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 36, 'order_id' => 19, 'purchasable_id' => 2, 'cart_item_id' => 43, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 3, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 7500, 'total_with_taxes' => 8625, 'computed_taxes' => 1125, 'created_at' => '2026-04-07 14:54:57', 'updated_at' => '2026-04-07 14:56:00', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 37, 'order_id' => 20, 'purchasable_id' => 2, 'cart_item_id' => 45, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-07 15:55:22', 'updated_at' => '2026-04-07 15:55:22', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 38, 'order_id' => 20, 'purchasable_id' => 14, 'cart_item_id' => 46, 'title' => 'Buzo Todo Ocasión', 'slug' => 'buzo-todo-ocasion', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2700, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2700, 'total_with_taxes' => 3105, 'computed_taxes' => 405, 'created_at' => '2026-04-07 15:55:22', 'updated_at' => '2026-04-07 15:55:22', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 57, 'order_id' => 30, 'purchasable_id' => 9, 'cart_item_id' => 59, 'title' => 'Suéter Clásico de Punto Pullóver', 'slug' => 'sueter-clasico-de-punto-pullover', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 5000, 'total_with_taxes' => 5750, 'computed_taxes' => 750, 'created_at' => '2026-04-08 13:01:34', 'updated_at' => '2026-04-08 13:01:34', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 58, 'order_id' => 30, 'purchasable_id' => 5, 'cart_item_id' => 58, 'title' => 'Pijama Confort Nube Nueve', 'slug' => 'pijama-confort-nube-nueve', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3200, 'quantity' => 3, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 9600, 'total_with_taxes' => 11040, 'computed_taxes' => 1440, 'created_at' => '2026-04-08 13:01:34', 'updated_at' => '2026-04-08 13:01:34', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 59, 'order_id' => 31, 'purchasable_id' => 14, 'cart_item_id' => 60, 'title' => 'Buzo Todo Ocasión', 'slug' => 'buzo-todo-ocasion', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2700, 'quantity' => 2, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 5400, 'total_with_taxes' => 6210, 'computed_taxes' => 810, 'created_at' => '2026-04-08 13:03:34', 'updated_at' => '2026-04-08 13:03:34', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 60, 'order_id' => 31, 'purchasable_id' => 15, 'cart_item_id' => 61, 'title' => 'Mono Beach Style', 'slug' => 'mono-beach-style', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2100, 'quantity' => 4, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 8400, 'total_with_taxes' => 9660, 'computed_taxes' => 1260, 'created_at' => '2026-04-08 13:03:34', 'updated_at' => '2026-04-08 13:03:34', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 61, 'order_id' => 32, 'purchasable_id' => 9, 'cart_item_id' => 62, 'title' => 'Suéter Clásico de Punto Pullóver', 'slug' => 'sueter-clasico-de-punto-pullover', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-08 14:50:19', 'updated_at' => '2026-04-08 14:50:19', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 62, 'order_id' => 32, 'purchasable_id' => 15, 'cart_item_id' => 63, 'title' => 'Mono Beach Style', 'slug' => 'mono-beach-style', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2100, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2100, 'total_with_taxes' => 2415, 'computed_taxes' => 315, 'created_at' => '2026-04-08 14:50:19', 'updated_at' => '2026-04-08 14:50:19', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 63, 'order_id' => 33, 'purchasable_id' => 1, 'cart_item_id' => 64, 'title' => 'Chaqueta Guardián Todo Clima', 'slug' => 'chaqueta-guardian-todo-clima', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 4800, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 4800, 'total_with_taxes' => 5520, 'computed_taxes' => 720, 'created_at' => '2026-04-08 14:51:43', 'updated_at' => '2026-04-08 14:51:43', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 64, 'order_id' => 33, 'purchasable_id' => 2, 'cart_item_id' => 65, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-08 14:51:43', 'updated_at' => '2026-04-08 14:51:43', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 65, 'order_id' => 34, 'purchasable_id' => 2, 'cart_item_id' => 66, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-08 14:56:39', 'updated_at' => '2026-04-08 14:56:39', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 66, 'order_id' => 34, 'purchasable_id' => 3, 'cart_item_id' => 67, 'title' => 'Cortavientos Transpirable Pionero', 'slug' => 'cortavientos-transpirable-pionero', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 3900, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 3900, 'total_with_taxes' => 4485, 'computed_taxes' => 585, 'created_at' => '2026-04-08 14:56:39', 'updated_at' => '2026-04-08 14:56:39', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
            ['id' => 67, 'order_id' => 35, 'purchasable_id' => 2, 'cart_item_id' => 76, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'image' => null, 'purchasable_type' => 'App\Models\Product', 'price' => 2500, 'quantity' => 1, 'taxes' => '[{"name":"IVA","percentage":15}]', 'total' => 2500, 'total_with_taxes' => 2875, 'computed_taxes' => 375, 'created_at' => '2026-04-09 19:44:32', 'updated_at' => '2026-04-09 19:44:32', 'has_discount' => false, 'discount_percentage' => 0, 'discounted_price' => 0],
        ]);
    }
}