<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            ['id' => 1, 'title' => 'Chaqueta Guardián Todo Clima', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Cubierta impermeable con forro polar, ribetes reflectantes y capucha ajustable para máxima protección contra el frío y la lluvia."}]}]}', 'main_image' => '01KB6CWRYQ9CWAG0YK9KVANWNV.jpg', 'video' => null, 'sku' => '8315420908280', 'slug' => 'chaqueta-guardian-todo-clima', 'status' => 'publicado', 'price' => 4800, 'stock' => 40, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[{"name":"color","values":[{"value":"Amarillo"},{"value":"Verde"}]},{"name":"Talla","values":[{"value":"S"},{"value":"M"},{"value":"L"}]}]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-11-28 23:31:19', 'summary' => null],
            ['id' => 2, 'title' => 'Poncho Anti-Salpicaduras Día de Lluvia', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Poncho de PVC ligero y transparente con correa segura para el pecho, perfecto para lluvias rápidas sin sobrecalentar."}]}]}', 'main_image' => '01KBE66HGN8F6WSX703M8RVVGQ.jpg', 'video' => null, 'sku' => '8912557432772', 'slug' => 'poncho-anti-salpicaduras-dia-de-lluvia', 'status' => 'publicado', 'price' => 2500, 'stock' => 95, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 00:08:11', 'summary' => null],
            ['id' => 3, 'title' => 'Cortavientos Transpirable Pionero', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Chaqueta de nylon ligera y plegable diseñada para bloquear el viento mientras se mantiene transpirable para excursiones activas al aire libre."}]}]}', 'main_image' => '01KBE6D162S8FDY3XKM7A2T8D6.jpg', 'video' => null, 'sku' => '3551564810958', 'slug' => 'cortavientos-transpirable-pionero', 'status' => 'publicado', 'price' => 3900, 'stock' => 23, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 00:11:44', 'summary' => null],
            ['id' => 4, 'title' => 'Chaleco Aislado Antártico', 'description' => '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Chaleco altamente aislado con relleno de plumón sintético, diseñado para proporcionar calor central a mascotas de pelo corto o mayores en frío extremo."}],"attrs":{"textAlign":"start"}}}', 'main_image' => '01KBECXRH3H2GE4RGN064EDVQ2.jpg', 'video' => null, 'sku' => '5221980200449', 'slug' => 'chaleco-aislado-antartico', 'status' => 'publicado', 'price' => 3500, 'stock' => 75, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:05:44', 'summary' => null],
            ['id' => 5, 'title' => 'Pijama Confort Nube Nueve', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Pijama de punto jersey ultrasuave y transpirable de cuatro patas, ideal para mantenerlos cómodos y reducir la caída de pelo en los muebles."}]}]}', 'main_image' => '01KBED3EZHRTV5BV3CJBHRADHV.jpg', 'video' => null, 'sku' => '2418235990061', 'slug' => 'pijama-confort-nube-nueve', 'status' => 'publicado', 'price' => 3200, 'stock' => 40, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[{"name":"color","values":[{"value":"amarillo"},{"value":"azul"}]},{"name":"talla","values":[{"value":"SM"},{"value":"M"},{"value":"L"}]}]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:08:53', 'summary' => null],
            ['id' => 6, 'title' => 'Bata Secante Post-Juego', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Bata de tela de rizo con cierre de lazo simple y capucha, ideal para secar y calentar rápidamente a las mascotas después del baño o un paseo húmedo."}]}]}', 'main_image' => '01KBED9XPMAXPXMX6FNTTZ5BJQ.jpg', 'video' => null, 'sku' => '8398002318622', 'slug' => 'bata-secante-post-juego', 'status' => 'publicado', 'price' => 2200, 'stock' => 37, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:12:25', 'summary' => null],
            ['id' => 7, 'title' => 'Mono de Descanso Ligero', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Un body de punto elástico y delgado que ayuda a contener la caída de pelo mientras ofrece comodidad total para pieles sensibles durante el descanso."}]}]}', 'main_image' => '01KBEDDJ383VRWPNVWTSYDKYD3.jpg', 'video' => null, 'sku' => '7089395504129', 'slug' => 'mono-de-descanso-ligero', 'status' => 'publicado', 'price' => 2700, 'stock' => 19, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:14:20', 'summary' => null],
            ['id' => 8, 'title' => 'Conjunto Lounge de Terciopelo de Lujo', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Conjunto de dos piezas (parte superior e inferior) hecho de terciopelo suave y elegante, perfecto para el estilo relajado de una mascota en casa."}]}]}', 'main_image' => '01KBEDHJQMK1RDH5X5615N0KM4.jpg', 'video' => 'https://res.cloudinary.com/dfpkdo5tf/video/upload/v1764199289/toecommerce/generated-video-3a7d6bd5-2957-4dfa-b14b-8b8c4ed06710.mp4', 'sku' => '6759134349571', 'slug' => 'conjunto-lounge-de-terciopelo-de-lujo', 'status' => 'publicado', 'price' => 3000, 'stock' => 165, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:16:36', 'summary' => null],
            ['id' => 9, 'title' => 'Suéter Clásico de Punto Pullóver', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Suéter de punto acanalado simple hecho de una mezcla de acrílico suave, un esencial de vestuario versátil para el día a día. Disponible en 5 colores."}]}]}', 'main_image' => '01KBEDTJW6A90NB05213VM7DCW.jpg', 'video' => null, 'sku' => '3862685865919', 'slug' => 'sueter-clasico-de-punto-pullover', 'status' => 'publicado', 'price' => 2500, 'stock' => 80, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[{"name":"color","values":[{"value":"rojo"},{"value":"violeta"}]}]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:21:28', 'summary' => null],
            ['id' => 10, 'title' => 'Suéter Navidad', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Acogedor suéter de punto en tonos otoñales cálidos, con un pequeño detalle bordado de pavo o calabaza en la espalda. Ideal para cenas familiares."}]}]}', 'main_image' => '01KBEE4AX6MF3R0G2R2ZZGAFN8.jpg', 'video' => null, 'sku' => '4903929111313', 'slug' => 'sueter-navidad', 'status' => 'publicado', 'price' => 3200, 'stock' => 178, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[{"name":"color","values":[{"value":"verde"},{"value":"rojo"}]},{"name":"sexo","values":[{"value":"macho"},{"value":"hembra"}]}]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:26:53', 'summary' => null],
            ['id' => 11, 'title' => 'Dog Dracula', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Disfraz capa de drácula"}]}]}', 'main_image' => '01KBEEAFAKB6YQ9PDSSE4787FA.jpg', 'video' => null, 'sku' => '2604144014213', 'slug' => 'dog-dracula', 'status' => 'publicado', 'price' => 2300, 'stock' => 90, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:30:07', 'summary' => null],
            ['id' => 12, 'title' => 'Ayudante de Santa', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Disfraz de Ayudante de Santa para perrito"}]}]}', 'main_image' => '01KBEEE3VPZVK9ZS40D8D7J2WB.jpg', 'video' => null, 'sku' => '7148956048882', 'slug' => 'ayudante-de-santa', 'status' => 'publicado', 'price' => 2250, 'stock' => 50, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:32:10', 'summary' => null],
            ['id' => 13, 'title' => 'Happy Hook', 'description' => '{"type":"doc","content":[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Un hook para toda ocasión o celebración. Especial para Navidad o San Valentín"}]}]}', 'main_image' => '01KBEEJJC6329H0VERB0JXED2J.jpg', 'video' => null, 'sku' => '0768383061673', 'slug' => 'happy-hook', 'status' => 'publicado', 'price' => 4000, 'stock' => 158, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => null, 'created_at' => '2025-11-23 00:41:49', 'updated_at' => '2025-12-02 02:34:38', 'summary' => null],
            ['id' => 14, 'title' => 'Buzo Todo Ocasión', 'description' => '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Un buso cómodo para toda salida con tu peludo"}],"attrs":{"textAlign":"start"}}}', 'main_image' => '01KBEEQRB2EG02NJP12YZTR9N1.jpg', 'video' => null, 'sku' => '790708080', 'slug' => 'buzo-todo-ocasion', 'status' => 'publicado', 'price' => 2700, 'stock' => 98, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => 2, 'created_at' => '2025-11-26 21:40:02', 'updated_at' => '2025-12-02 02:37:27', 'summary' => null],
            ['id' => 15, 'title' => 'Mono Beach Style', 'description' => '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Mono relajante que le da comfort y alegría a tu mascota"}],"attrs":{"textAlign":"start"}}}', 'main_image' => '01KBEEYHJ1HTT4MDW6Z5MDX9QF.jpg', 'video' => null, 'sku' => '869790700', 'slug' => 'mono-beach-style', 'status' => 'publicado', 'price' => 2100, 'stock' => 60, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => 2, 'created_at' => '2025-11-26 21:52:26', 'updated_at' => '2025-12-02 02:41:10', 'summary' => null],
            ['id' => 16, 'title' => 'Lounge Time', 'description' => '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Buso comodidad y relajación máxima para tu mascota"}],"attrs":{"textAlign":"start"}}}', 'main_image' => '01KBEF2NX3D0J73RMDJP4SF5K8.jpg', 'video' => null, 'sku' => '87979797', 'slug' => 'lounge-time', 'status' => 'publicado', 'price' => 2300, 'stock' => 32, 'stock_threshold_for_customers' => 10, 'tags' => null, 'variant_options' => '[]', 'published_at' => '2025-11-26 23:30:41', 'archived_at' => null, 'user_id' => 2, 'created_at' => '2025-11-26 22:01:17', 'updated_at' => '2025-12-02 02:43:25', 'summary' => null],
        ]);
    }
}